### ISSUE TITLE
Color generetor button bug

### ISSUE THREAD

**Issue by bymustfa** [efsanegnyl/randomColorJs#1]
Renk oluşturmayı sağlayan buttona mouse ile click işleminin ardından sayfanın butona focus olması nedeni ile space tusşuna basıldığında hem buttonun click fonksiyonu tekrar çalışıyor hemde space tuşuna atanan fonksiyon.
Bu nedenle ekranda 2 defa yeni renk oluşturuluyor.

Öneri:
button a click işleminden sonra focus işemini devredışı bırakmak
` button.blur() ` kodu kullanılabilir.

**Comment by efsanegnyl** [comment]
Teşekkürler, blur() kodu ile sorunu çözdüm
